### ISSUE TITLE
landpage/courses

### ISSUE THREAD

**Issue by bartmika** [AcademicsToday/py-academicstoday#3]
# Replace these stubs with our information
![screen shot 2015-02-15 at 9 10 48 pm](https://cloud.githubusercontent.com/assets/5767602/6206421/68d6181a-b557-11e4-81f3-3a273e293b59.png)

**Comment by Sebastian-Rydzewski** [comment]
My idea is to showcase 6 courses from our active ones.

My thoughts are on an automated pick-top-six of courses that had the highest popularity/traffic for the past 30 days, and this would be calculated and updated in the database every 24 or 12 hours, pulled from a table in the database called [TopSix].  This might be a preferable method rather than doing the calculation each time the landing page is loaded; It may not seem like much of a strain on the load time, but down the road with growing web traffic it is possible it will strain the system's processing causing some lag,

**Comment by bartmika** [comment]
@Sebastian-Rydzewski Your idea has been implemented.

**Comment by bartmika** [comment]
Developers note: We are using https://github.com/Tivix/django-cron for running separate processes ever 30 days.
